apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rics-operators
  namespace: olm
spec:
  sourceType: grpc
  image: ricfeatherstone/demo-operator-catalog:latest
  displayName: Ric's Operators
  publisher: ricfeatherstone
  updateStrategy:
    registryPoll:
      interval: 10m
