
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: demo-operator-system
rules:
- apiGroups:
  - demo.ricfeatherstone.com
  resources:
  - noops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.ricfeatherstone.com
  resources:
  - noops/finalizers
  verbs:
  - update
- apiGroups:
  - demo.ricfeatherstone.com
  resources:
  - noops/status
  verbs:
  - get
  - patch
  - update
